general {
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
    ignore_wayland_inhibit = false
}

listener {
            timeout = 600
            on-timeout = hyprctl dispatch dpms off
            on-resume = hyprctl dispatch dpms on
}

listener {
            timeout = 1800
            on-timeout = systemctl suspend
}




