-- vim: ft=conky
conky.config = {
    alignment = 'top_right',
    gap_x = 10,
    gap_y = 60,
    background = false,
    own_window = true,
    own_window_type = 'override',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 180,
    draw_shades = false,
    draw_outline = true,
    short_units = true,
    double_buffer = true,
    update_interval = 1.0,
    minimum_width = 300,
    maximum_width = 300,
    use_xft = true,
    font = 'JetBrainsMono Nerd Font Mono:size=10',
}

conky.text = [[
${hr 1}
CPU: ${alignr}${cpu cpu0}% @ ${freq_g}GHz
Temp ${alignr}${hwmon 0 temp 1}°C
RAM: ${alignr}${mem}/${memmax}
Disk: ${alignr}${fs_used /}/${fs_size /}
Top CPU:  ${top name 1} ${alignr}${top cpu 1}%
Top MEM: ${top_mem name 1} ${alignr}${top_mem mem_res 1}
${hr 1}
]]

