#!/bin/bash

install_sound_system() {
    sudo pacman -S --needed pipewire pipewire-pulse wireplumber
    systemctl --user --now enable pipewire pipewire-pulse wireplumber
}

install_basics() {
    # Basics
    sudo pacman -S swayimg swaybg webp-pixbuf-loader grim slurp wl-clipboard wf-recorder lftp wev unarchiver udiskie \
    fd fzf fuzzel mpd mpc mpv pass ncmpcpp neomutt neovim \
    isync msmtp rclone yt-dlp zathura zathura-djvu zathura-pdf-poppler \
    adobe-source-han-sans-otc-fonts sound-theme-freedesktop qt5-wayland python-tldextract 

    yay qt5ct xdg-desktop-portal-hyprland-git puddletag perl-mime-encwords

    # Mpris and printer
    sudo pacman -S playerctl mpv-mpris simple-scan
    yay mpd-mpris-bin hplip-plugin hplip numbat newsraft-git sane sane-airscan

    # Appimage
    sudo pacman -S fuse

    # Enable services
    systemctl --user enable --now mpd-mpris
}

install_texlive_packages() {
    # texlive bits
    yay texlive-meta texlive-langspanish texlab
}

enable_services () {
    systemctl daemon-reload 

    echo "Starting user timers"
    systemctl --user enable --now mpd.service mbsync.timer

    echo "Starting system timers"
    systemctl enable --now fstrim.timer
}


usage() {
    echo "$0: First Setup:"
    echo
    echo "Usage: $0 [-sbth]"
    echo
    echo "-s: Install sound system" 
    echo "-p: Install programs and enable services"
    echo "-t: Install TeXlive packages"
    echo "-h: print this usage text and exit"
}

if [ $# -lt 1 ]
then
    yadm sparse-checkout set --no-cone '/*' '!LICENSE'
    usage
    exit 1
fi

# parse options
while getopts "sdbth" OPTION; do
    case $OPTION in
        s)
            install_sound_system
            break;;
        b)
            install_basics
            enable_services
            ;;
        t)
            install_texlive_packages
            ;;
        h)
            usage
            ;;
    esac
done
