#!/bin/bash

install_basics() {
    # Multimedia 
        

    # Basics
    sudo pacman -Syu feh grim slurp wl clipboard wf-recorder lftp wev w3m unarchiver \
    easytag fd fzf mpd mpc mpv pass ncmpcpp neomutt neovim rofi yt-dlp \
    isync msmtp zathura\
    adobe-source-han-sans-otc-fonts sound-theme-freedesktop 

    yay newsraft-git
 
    # hplip, hplip-gui for hp printers drivers and simple-scan
}

install_texlive_packages() {
    # texlive bits
    # sudo pacman -Syu install texlive latexmk
}

enable_services () {
    systemctl daemon-reload 

    echo "Starting/enabling mpd service"
    systemctl --user enable --now mpd.service 

    echo "Starting user timers"
    systemctl enable --now mbsync.timer

    echo "dnf-makecache"
    systemctl disable --now dnf-makecache.timer
}


usage() {
    echo "$0: Install packages and software"
    echo
    echo "Usage: $0 [-bth]"
    echo
    echo "-b: install basics and enable services"
    echo "-t: install TeXlive packages"
    echo "-h: print this usage text and exit"
}

if [ $# -lt 1 ]
then
    usage
    exit 1
fi

# parse options
while getopts "dbth" OPTION; do
    case $OPTION in
        b)
            install_basics
            enable_services
            exit 0
            ;;
        t)
            install_texlive_packages
            exit 0
            ;;
        h)
            usage
            exit 0
            ;;
    esac
done
