#!/bin/bash

install_sound_system() {
    sudo pacman -S --needed pipewire pipewire-pulse wireplumber
    systemctl --user --now enable pipewire pipewire-pulse wireplumber
}

install_basics() {
    # Basics
    sudo pacman -S bc feh grim slurp wl-clipboard wf-recorder lftp wev w3m unarchiver \
    fd fzf mpd mpc mpv pass ncmpcpp neomutt neovim \
    isync msmtp rclone yt-dlp zathura \
    adobe-source-han-sans-otc-fonts sound-theme-freedesktop qt5-wayland

    yay xdg-desktop-portal-hyprland-git puddletag newsraft-git perl-mime-encwords

    systemctl --user mask xdg-desktop-portal
 
    # hplip, hplip-gui for hp printers drivers and simple-scan
}

install_texlive_packages() {
    # texlive bits
    sudo pacman -S install texlive-mathscience texlive-binextra zathura-pdf-poppler
}

enable_services () {
    systemctl daemon-reload 

    echo "Starting user timers"
    systemctl --user enable --now mpd.service mbsync.timer

    echo "Starting system timers"
    systemctl enable --now fstrim.timer
}


usage() {
    echo "$0: First Setup:"
    echo
    echo "Usage: $0 [-sbth]"
    echo
    echo "-s: Install sound system" 
    echo "-p: Install programs and enable services"
    echo "-t: Install TeXlive packages"
    echo "-h: print this usage text and exit"
}

if [ $# -lt 1 ]
then
    usage
    exit 1
fi

# parse options
while getopts "sdbth" OPTION; do
    case $OPTION in
        s)
            install_sound_system
            break;;
        b)
            install_basics
            enable_services
            ;;
        t)
            install_texlive_packages
            ;;
        h)
            usage
            ;;
    esac
done
