#Make mpv works with yt-dl fork yt-dlp
#script-opts-append=ytdl_hook-ytdl_path=yt-dlp

## General ##
hwdec=vaapi
vo=gpu
gpu-context=wayland
border=no
no-window-dragging
volume-max=100
save-position-on-quit
screenshot-directory="~/MediaHub/screenshots/mpv"
watch-later-directory="~/.local/state/mpv/"
log-file="~/mpv.log"

## OSD ##
osd-on-seek=msg-bar
osd-font='JetBrainsMono Nerd Font'
osd-font-size=20
osd-color="#FFFFFF"
cursor-autohide=500
osd-status-msg='${time-pos} | 󰃨 ${demuxer-cache-duration}'

## OSD-BAR ##
osd-bar-h=0.8               # height as a percentage of your screen height
osd-bar-w=60              # width of " " "
osd-bar-align-y=-0.980      # progress bar y alignment (-1 top, 0 centered, 1 bottom)
osd-border-size=2 	        # border size for osd text and progress bar

## Languages ##
slang=eng,en,enUS,en-US,spa,es
alang=Japanese,jpn,ja,eng,en,enUS,en-US,spa,es

## Subtitles ##
sub-auto=fuzzy
sub-font-size=36
sub-border-size=1.5
sub-scale-by-window=no

## Streaming ##
ytdl-format=bestvideo[height<=?1080]+bestaudio/best
cache=yes               # Use a large seekable RAM cache even for local input
demuxer-max-bytes=500MiB
demuxer-max-back-bytes=100MiB
demuxer-readahead-secs=20

[not fullscreen]
profile-restore=copy
profile-cond=(osd_width < 1280 )
video-zoom=0.2
sub-font-size=28

[osc]
profile-restore=copy
profile-cond=(osd_height < 720 )
osc=no

[loop-cond]
profile-cond = (filename:match"%.gif[v]?$" or filename:match"%.webm$") ~= nil
cache=no
no-pause
loop-file=yes

[youtube]
profile-cond=path:find('youtu%.?be') ~= nil or path:find('watch%?v=') ~= nil
ytdl-format=[height<=?720]
