conky.config = {
  update_interval = 1,
  own_windoe_class = 'Conky',
	own_window = true,
	own_window_transparent = false,
	own_window_type = 'normal',
	own_window_argb_visual = true,
	own_window_argb_value = 180,
  double_buffer = true,
  alignment = 'bottom_right',
  use_xft = true,

  font = 'JetBrainsMono Nerd Font Mono:size=12',
  default_color = 'DDDDDD',
  draw_shades = true,
  draw_outline = false,
  maximum_width = 50,
};

conky.text = [[
${alignc}${time %H:%M} 
]];

