[pyprland]
plugins = [
    "scratchpads",
]

[scratchpads.newsraft]
command = "foot --app-id=floating --title=newsraft newsraft"
lazy = true
excludes = ["neomutt"]

[scratchpads.neomutt]
command = "foot --app-id=floating --title=neomutt neomutt"
lazy = true
excludes = ["newsraft"]

[scratchpads.floatterm]
command = "TMOUT=0 foot --app-id=floating"
lazy = true

[scratchpads.utilities]
command = "foot --app-id=floating ~/bin/utilities.sh"
lazy = true

[scratchpads.trans]
animation = "fromBottom"
command = "foot --app-id=floating trans -4 -I"
lazy = true

