
windowrule = workspace special:newsraft silent, newsraftsilent

workspace = special:jerry, on-created-empty: $terminal --app-id=jerry jerry
workspace = special:launcher, on-created-empty:$terminal --app-id=launcher ~/bin/lib/launcher-desktop.sh
workspace = special:trans, on-created-empty:$terminal --app-id=trans trans -b :@es 
workspace = special:transI, on-created-empty:$terminal --app-id=transI trans -b -I :@es 
workspace = special:neomutt, on-created-empty:$terminal --app-id=neomutt neomutt
workspace = special:newsraft, on-created-empty:$terminal --app-id=newsraftsilent newsraft
workspace = special:utilities, on-created-empty:$terminal --app-id=utilities ~/bin/utilities.sh
workspace = special:floatterm, on-created-empty:TMOUT=0 $terminal --app-id=floatterm

bind = $mainMod, A, togglespecialworkspace, jerry
bind = $mainMod, R, togglespecialworkspace, launcher
bind = $mainMod, KP_End, togglespecialworkspace, transI 
bind = $mainMod SHIFT, KP_End, togglespecialworkspace, trans 
bind = $mainMod, KP_Down, togglespecialworkspace, neomutt 
bind = $mainMod, KP_Next, togglespecialworkspace, newsraft
bind = $mainMod, KP_Begin, togglespecialworkspace, utilities 
bind = $mainMod, KP_Home, togglespecialworkspace, floatterm 

bind = $mainMod Shift, KP_Home, movetoworkspace, special:floatterm 

