follow_outside_symlinks     "yes"
follow_inside_symlinks      "yes"
db_file "~/.config/mpd/database"
music_directory "~/Music/2015-2022"
auto_update "yes"

user			"edwin"

audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
        format          "44100:16:1"
}



