
db_file "~/.config/mpd/database"
music_directory "~/Music/2015-2022"
auto_update "yes"
playlist_directory     "~/.config/mpd/playlists"

user			"edwin"

audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
        format          "44100:16:1"
    echo "Check the installed Audio Server"
}



