#!/usr/bin/env bash
set -u

source "$HOME/.local/share/linuxfedora"

mbsyncrc="$HOME/nix/dotfiles/neomutt/.mbsyncrc"
marker="$HOME/.config/neomutt/.mailsynclast"
prefix="$HOME/.local/share/email/gmail"

[ ! -r "$mbsyncrc" ] && exit 0
[ ! -d "$prefix" ] && exit 0

lock="${XDG_RUNTIME_DIR:-/tmp}/mailsync.lock"
exec 9>"$lock"
flock -n 9 || exit 0

touch "$marker"
mbsync -c "$mbsyncrc" gmail || exit 1

for file in "$prefix"/*; do
    folder="${file#"$prefix"/}"

    case "$folder" in
        INBOX|Github|Interbank) ;;
        *) continue ;;
    esac

    find "$file/new" -type f -newer "$marker" -print0 2>/dev/null |
    while IFS= read -r -d '' newemail; do
        sender="$(
            sed -n '/^From: /s/^From: //p' "$newemail" |
            perl -pe 'use MIME::EncWords(decode_mimewords); $_=decode_mimewords($_);'
        )"

        subject="$(
            sed -n '/^Subject: /s/^Subject: //p' "$newemail" |
            perl -pe 'use MIME::EncWords(decode_mimewords); $_=decode_mimewords($_);'
        )"

        [[ -n "$sender" && -n "$subject" ]] &&
            notify-send -t 30000 "$sender" "$subject"
    done
done
