#!/usr/bin/env bash

trap "echo 'Script interrupted. Exiting...'; exit" SIGINT

# Define directories
dir=~/Music/MainPL
cd ~/Music
mkdir -p "$dir"

declare -A chill=(
    ["https://www.youtube.com/playlist?list=PL4CmunqMOJjKi1Mtlc3N5pedFJ5UgFobk"]="The Hall"
)

download_playlists() {
    declare -n playlists="$1"

    for url in "${!playlists[@]}"; do
        artist="${playlists[$url]}"

    echo -e "\e[1;32mDownloading $artist's playlist...\e[0m"

    yt-dlp --progress --parse-metadata " $artist: %(meta_artist)s" -o "$dir/%(title)s_%(id)s.%(ext)s" "$url"
    done
}
download_playlists chill
