#!/usr/bin/env bash

get_state() {
    wpctl get-volume "$1" |
    awk '{v=int($2*100); m=$3~/MUTED/?1:0; print v,m}'
}

case "$1" in
    up|down|mute) node="@DEFAULT_SINK@"    type="volume" ;;
    mute-mic)     node="@DEFAULT_SOURCE@"  type="microphone" ;;
esac

read vol muted < <(get_state "$node")

case "$1" in
    up|down)
        wpctl set-mute "$node" 0 && muted=0
        if [[ $1 == up ]]; then
            new_vol=$((vol + 5))
        else
            new_vol=$((vol - 5))
        fi
        new_vol=$((new_vol < 0 ? 0 : new_vol > 100 ? 100 : new_vol))
        wpctl set-volume "$node" "$new_vol%"
        vol=$new_vol ;;
    mute*)
        wpctl set-mute "$node" toggle
        read vol muted < <(get_state "$node")
        ;;
esac

if ((muted)); then
    if [[ $type == "volume" ]]; then
        msg="🔇 muted"
    else
        msg="🤐 mic muted"
    fi
    timeout="-t 0"
else
    if [[ $type == "volume" ]]; then
        if ((vol <= 30)); then
            msg="🔈 $vol%"
        elif ((vol <= 60)); then
            msg="🔉 $vol%"
        else
            msg="🔊 $vol%"
        fi
        progress_hint=(-h "int:value:$vol")
    else
        msg="🎤 mic unmuted"
    fi
    timeout="-t 1000"
fi

notify-send -u normal \
    -h "string:x-canonical-private-synchronous:${type}" \
    "${progress_hint[@]}" \
    "$msg" $timeout
