#Only ASCII in filename
--restrict-filenames

-o "%(title)s_%(id)s.%(ext)s"

#Audio format code
-f m4a

--parse-metadata "title:^(?:[\【\[].*?[\】\]]\s*|.*? -\s*)?(?P<title>.+?)(?:\s*\(\s*Audio\s*\))?$" --parse-metadata "playlist_title:%(artist)s"

--parse-metadata ":(?P<meta_synopsis>)(?P<meta_description>)(?P<meta_purl>)" --embed-metadata

# Filter
--match-filter "duration>300 & duration<1500"

# Unlist unavailable videos from playlists
--compat-options no-youtube-unavailable-videos

#Download only videos not listed in the archive file. Record the IDs of all
--download-archive  ~/bin/misc/yt-dlp/2015-2020.txt


