#!/run/current-system/sw/bin/bash

# Function to extract the original YouTube URL from DuckDuckGo lite redirect URL
extract_youtube_url() {
    # Decode URL-encoded string
    local url=$(echo -e "$(printf '%b' "${1//%/\\x}")")
    # Extract the YouTube URL
    local youtube_url="${url##*uddg=}"
    echo "$youtube_url"
}

case $QUTE_URL in
    *duckduckgo.com/l/?uddg=*)
        original_url=$(extract_youtube_url "$QUTE_URL")
        mpv "$original_url" &>/dev/null &exit
        ;;
	*)
        mpv "$QUTE_URL" &>/dev/null &exit
        ;;
esac
