#!/bin/bash

# Function to extract the original YouTube URL from DuckDuckGo lite redirect URL
extract_youtube_url() {
    # Decode URL-encoded string
    local url=$(echo -e "$(printf '%b' "${1//%/\\x}")")
    # Extract the YouTube URL
    local youtube_url="${url##*uddg=}"
    echo "$youtube_url"
}

case $QUTE_URL in
    *youtube.com/shorts/*)
        mpv --volume=35 --loop-file=inf "$QUTE_URL" &>/dev/null &exit
        ;;
    *duckduckgo.com/l/?uddg=*)
        original_url=$(extract_youtube_url "$QUTE_URL")
        mpv --volume=35 "$original_url" &>/dev/null &exit
        ;;
	*)
        mpv --volume=35 "$QUTE_URL" &>/dev/null &exit
        ;;
esac
